version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 7000:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /tmp/logs:/var/log/nginx

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo:/data/db

  app:
    build: .
    # restart: always
    command: npm start
    # environment:
    #   - TZ=Asia/Shanghai
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8803:8803
    depends_on:
      - redis
      - mongo
    links:
      - redis:rd
      - mongo:mg
